"""adicionar vinculo formal entre chat e decks gerados

Revision ID: a3f4fac6e8f4
Revises: c72b9acf2ec4
Create Date: 2026-04-16 19:38:44.752886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f4fac6e8f4'
down_revision: Union[str, None] = 'c72b9acf2ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_generated_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('generation_index', sa.Integer(), nullable=False),
    sa.Column('user_message_id', sa.Integer(), nullable=True),
    sa.Column('assistant_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'generation_index', name='uq_chat_generation_index')
    )
    op.create_index(op.f('ix_chat_generated_decks_deck_id'), 'chat_generated_decks', ['deck_id'], unique=False)
    op.create_index(op.f('ix_chat_generated_decks_id'), 'chat_generated_decks', ['id'], unique=False)
    op.create_index(op.f('ix_chat_generated_decks_session_id'), 'chat_generated_decks', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_generated_decks_session_id'), table_name='chat_generated_decks')
    op.drop_index(op.f('ix_chat_generated_decks_id'), table_name='chat_generated_decks')
    op.drop_index(op.f('ix_chat_generated_decks_deck_id'), table_name='chat_generated_decks')
    op.drop_table('chat_generated_decks')
    # ### end Alembic commands ###
